{
 "title": "MISP",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Logins",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"misp\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"audit\" and r[\"model\"] == \"user\" and r[\"action\"] == \"login\" and r[\"_field\"] == \"model_id\")\n  |> aggregateWindow(every: v.windowPeriod, fn: count)\n"
    },
    {
     "query": "from(bucket: \"misp\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"audit\" and r[\"model\"] == \"user\" and r[\"action\"] == \"login_fail\" and r[\"_field\"] == \"model_id\")\n  |> aggregateWindow(every: v.windowPeriod, fn: count)\n"
    }
   ]
  },
  {
   "title": "Latest Events",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 11, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"misp\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"event\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> sort(columns: [\"_time\"], desc: true)\n  |> drop(columns: [\"_start\", \"_stop\", \"_measurement\", \"id\", \"org_id\", \"published\"])"
    }
   ]
  },
  {
   "title": "Logins Today",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"misp\")\n  |> range(start: today())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"audit\" and r[\"model\"] == \"user\" and r[\"action\"] == \"login\" and r[\"_field\"] == \"model_id\")\n  |> count()"
    }
   ]
  },
  {
   "title": "New Events Today",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"misp\")\n  |> range(start: today())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"audit\")\n  |> filter(fn: (r) => r[\"model\"] == \"event\" and r[\"action\"] == \"add\" and r[\"_field\"] == \"model_id\")\n  |> count()"
    }
   ]
  },
  {
   "title": "Events",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"misp\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"audit\" and r[\"model\"] == \"event\" and r[\"action\"] == \"add\" and r[\"_field\"] == \"model_id\")\n  |> aggregateWindow(every: v.windowPeriod, fn: count)\n"
    },
    {
     "query": "from(bucket: \"misp\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"audit\" and r[\"model\"] == \"event\" and r[\"action\"] == \"publish\" and r[\"_field\"] == \"model_id\")\n  |> aggregateWindow(every: v.windowPeriod, fn: count)\n"
    }
   ]
  },
  {
   "title": "Attribute Types",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"misp\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"attribute\" and r[\"_field\"] == \"id\")\n  |> group(columns: [\"type\"], mode:\"by\")\n  |> count()\n"
    }
   ]
  },
  {
   "title": "Attribute Categories",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 16, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"misp\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"attribute\" and r[\"_field\"] == \"id\")\n  |> group(columns: [\"category\"], mode:\"by\")\n  |> count()\n"
    }
   ]
  },
  {
   "title": "New Attributes Today",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"misp\")\n  |> range(start: today())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"audit\")\n  |> filter(fn: (r) => r[\"model\"] == \"attribute\" and r[\"action\"] == \"add\" and r[\"_field\"] == \"model_id\")\n  |> count()"
    }
   ]
  },
  {
   "title": "Emails sent Today",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"misp\")\n  |> range(start: today())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"audit\" and r[\"model\"] == \"user\" and r[\"action\"] == \"email\" and r[\"_field\"] == \"model_id\")\n  |> count()"
    }
   ]
  },
  {
   "title": "New Object/Attributes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"misp\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"audit\" and r[\"model\"] == \"attribute\" and r[\"action\"] == \"add\" and r[\"_field\"] == \"model_id\")\n  |> aggregateWindow(every: v.windowPeriod, fn: count)"
    },
    {
     "query": "from(bucket: \"misp\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"audit\" and r[\"model\"] == \"object\" and r[\"action\"] == \"add\" and r[\"_field\"] == \"model_id\")\n  |> aggregateWindow(every: v.windowPeriod, fn: count)"
    }
   ]
  },
  {
   "title": "HTTP requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 11, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"misp\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"misp_apache_access_log\" and  r[\"_field\"] == \"request\")\n  |> group(columns: [\"resp_code\"], mode:\"by\")\n  |> aggregateWindow(every: v.windowPeriod, fn: count)"
    }
   ]
  },
  {
   "title": "Avg. Response Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"misp\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"misp_apache_access_log\")\n  |> filter(fn: (r) => r[\"_field\"] == \"response_time\")\n  |> toFloat()\n  |> group()\n  |> median()"
    }
   ]
  },
  {
   "title": "Max. Response Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"misp\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"misp_apache_access_log\")\n  |> filter(fn: (r) => r[\"_field\"] == \"response_time\")\n  |> toFloat()\n  |> group()\n  |> max()"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 18 },
   "targets": [
    {
     "query": "from(bucket: \"misp\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"misp_error_log\" and r[\"_field\"] == \"log_entry_text\")\n  |> group(columns: [\"log_entry_type\"], mode:\"by\")\n  |> aggregateWindow(every: v.windowPeriod, fn: count)"
    }
   ]
  },
  {
   "title": "Error log",
   "type": "logs",
   "gridPos": { "h": 5, "w": 10, "x": 11, "y": 18 },
   "targets": [
    {
     "query": "from(bucket: \"misp\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"misp_error_log\" and r[\"_field\"] == \"log_entry_text\")\n"
    }
   ]
  },
  {
   "title": "ZMQ Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"misp\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"zmq_status\")\n  |> filter(fn: (r) => r[\"_field\"] == \"uptime\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Errors Today",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"misp\")\n  |> range(start: today())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"misp_error_log\" and r[\"log_entry_type\"] == \"Error\" and r[\"_field\"] == \"log_entry_text\")\n  |> count()"
    }
   ]
  },
  {
   "title": "New Users",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"misp\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"audit\" and r[\"model\"] == \"user\" and r[\"action\"] == \"add\")\n  |> aggregateWindow(every: v.windowPeriod, fn: count)"
    }
   ]
  }
 ]
}