{
 "title": "MISP Infra",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "HTTP Statuses",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"misp\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tail\")\n  |> filter(fn: (r) => r[\"_field\"] == \"request\")\n  |> group(columns: [\"resp_code\"], mode:\"by\")\n  |> aggregateWindow(every: v.windowPeriod, fn: count)"
    }
   ]
  },
  {
   "title": "Redis RAM usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"misp\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"redis\")\n  |> filter(fn: (r) => r._field == \"used_memory\" or r._field == \"used_memory_dataset\" or r._field == \"used_memory_rss\" or r._field == \"used_memory_lua\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n  "
    }
   ]
  },
  {
   "title": "RAM usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"misp\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\")\n  |> filter(fn: (r) => r[\"_field\"] == \"used_percent\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "CPU usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"misp\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\" or r[\"_field\"] == \"usage_user\")\n  |> filter(fn: (r) => r[\"cpu\"] == \"cpu-total\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "SQL queries by type",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"misp\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mysql\")\n  |> filter(fn: (r) => r[\"_field\"] == \"com_insert\" or r[\"_field\"] == \"com_update\" or r[\"_field\"] == \"com_select\" or r[\"_field\"] == \"com_delete\")\n  |> derivative(unit: v.windowPeriod, nonNegative: false)\n  |> yield(name: \"derivative\")"
    }
   ]
  },
  {
   "title": "Redis Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 11, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"misp\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"redis\")\n  |> filter(fn: (r) => r._field == \"total_net_output_bytes\" or r._field == \"total_net_input_bytes\")\n  |> derivative(unit: v.windowPeriod, nonNegative: false)\n  |> yield(name: \"derivative\")"
    }
   ]
  },
  {
   "title": "Redis Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"misp\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"redis\")\n  |> filter(fn: (r) => r._field == \"uptime\")\n  |> last()\n  |> map(fn: (r) => ({r with _value: float(v: r._value) / 86400.0}))\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Redis connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"misp\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"redis\")\n  |> filter(fn: (r) => r._field == \"total_connections_received\" or r._field == \"rejected_connections\")\n  |> derivative(unit: 1s, nonNegative: false)\n  |> last()\n  |> group()\n  |> sum(column: \"_value\")"
    }
   ]
  },
  {
   "title": "MySQL connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"misp\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mysql\")\n  |> filter(fn: (r) => r[\"_field\"] == \"connections\")\n  |> derivative(unit: v.windowPeriod, nonNegative: false)\n  |> yield(name: \"derivative\")"
    }
   ]
  },
  {
   "title": "MySQL Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 11, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"misp\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r[\"_measurement\"] == \"mysql\")\n|> filter(fn: (r) => r[\"_field\"] == \"bytes_sent\" or r[\"_field\"] == \"bytes_received\")\n|> derivative(unit: v.windowPeriod, nonNegative: false)\n|> yield(name: \"derivative\")"
    }
   ]
  },
  {
   "title": "MySQL Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"misp\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mysql\")\n  |> filter(fn: (r) => r[\"_field\"] == \"uptime\")\n  |> last(column: \"_value\")\n  |> map(fn: (r) => ({ _time: r._time, _value: float(v: r._value) / 86400.00, _field: r._field, _measurement: r._measurement, host: r.host }))"
    }
   ]
  },
  {
   "title": "Total SQL Queries",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"misp\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mysql\")\n  |> last(column: \"_value\")\n  |> filter(fn: (r) => r[\"_field\"] == \"queries\")"
    }
   ]
  }
 ]
}